### ISSUE TITLE
Formatting the table and its contents

### ISSUE THREAD

**Issue by prajwalkpatil** [prakashbh/inventory-data-structure#1]
#### The table which used to look like this,
![old](https://user-images.githubusercontent.com/32927982/145703259-753584a5-85ce-4dd2-b384-a5bb5cbc9844.JPG)
 
#### Will look like this-
![new](https://user-images.githubusercontent.com/32927982/145703275-e32319de-2f92-4123-afd6-ecd316d5682e.JPG)

### This will work for values of any length.

I will be posting a pull request soon!

**Comment by prakashbh** [comment]
Thank you for the update. Will validate and approve the request.
